app:
    resource: "@AppBundle/Controller/"
    type:     annotation

rest:
    resource: "@AppBundle/Controller/Rest/"
    type: rest

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"