version: '2'
services:
  php:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
    ports:
      - 80:80
    volumes:
      - ..:/var/www/html

  db:
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=attendyDbPass
      - MYSQL_USER=attendyDbUser
      - MYSQL_DATABASE=attendy
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes